name: OpenAPI Validate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli
      - name: Validate OpenAPI
        run: spectral lint lab01/docs/openapi.yaml
